[".vim/bundle/Vundle.vim"]
    type = "archive"
    url = "https://github.com/VundleVim/Vundle.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["/usr/local/bin"]
    type = "archive"
    url = "https://github.com/rupa/z/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
