["bin/z"]
    type = "archive"
    url = "https://github.com/rupa/z/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["bin/tinymodt"]
    type = "archive"
    url = "https://github.com/bderenzo/tinymotd/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["bin/try/try"]
    type = "file"
    url = "https://raw.githubusercontent.com/binpash/try/main/try"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

