#!/bin/bash

curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
 sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg 2>&1 >/dev/null

sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
 sudo tee /etc/apt/sources.list.d/1password.list

sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
 sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
 sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

sudo apt-get update
sudo apt-get -y install \
  1password-cli \
  vim \
  zsh

# Download and install Starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

# Download and install Chezmoi
export GITHUB_USERNAME=michaelefisher
if [[ ! -f ".local/share/chezmoi/bootstrap" ]]; then
  printf '%s' "No bootstrap found, running Chezmoi..."
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME --config $HOME/dotfiles/chezmoi.toml
fi
