#!/bin/bash

# Download and install Starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

# Download and install Chezmoi
export GITHUB_USERNAME=michaelefisher
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME --config "$HOME"/.local/share/chezmoi/chezmoi.toml

