#!/bin/bash

# Download and install Starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

# Download and install Chezmoi
export GITHUB_USERNAME=michaelefisher
if [[ ! -f ".local/share/chezmoi/bootstrap" ]]; then
  printf '%s' "No bootstrap found, running Chezmoi..."
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME --config .local/share/chezmoi/chezmoi.toml
fi

