#!/usr/bin/env zsh

if [[ -z "$NVM_DIR" ]]; then
    export NVM_DIR="$HOME/.nvm"
fi

if [[ ! -f "$NVM_DIR/nvm.sh" ]]; then
    echo "nvm not found at $NVM_DIR" >&2
    return 1
fi

unfunction nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
command nvm "$@"