# Inserts a blank line between shell prompts
add_newline = true

#format="$all$directory$character"

[aws]
disabled = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style)  '

[memory]
disabled = false
