# Inserts a blank line between shell prompts
add_newline = true

#format="$all$directory$character"

[aws]
disabled = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style)  '

[memory_usage]
disabled = false

[nodejs]
disabled = true

[terraform]
format = "[$version$workspace]($style) "
symbol = "💠"
detect_folders = [".terraform"]

