# Inserts a blank line between shell prompts
add_newline = true

format="$all$directory$character"

#format = """
#$username\
#$hostname\
#$directory\
#$git_branch\
#$git_status\
#$nodejs\
#$terraform\
#$python\
#$ruby\
#$gcloud\
#$status\
#$shell\
#$character"""

[aws]
disabled = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style)  '
